### ISSUE TITLE
Please can you bump the version.

### ISSUE THREAD

**Issue by bigandy** [KeithHenry/chromeExtensionAsync#14]
You made a [commit](https://github.com/KeithHenry/chromeExtensionAsync/commit/afb804c55c99fdcb7ae18fab61f7500016c3aabf) that fixes [my issue](https://github.com/KeithHenry/chromeExtensionAsync/issues/10#issuecomment-453128968). Please can you release a bumped version so that I can use npm to install. Thanks!

**Comment by hereismass** [comment]
+1
Currently using github repo with your last commit as dependency in order to fix the same issue.
Can only agree for a bumped version :D

**Comment by KeithHenry** [comment]
Sorry for the delay. Now 3.3.1 on npm: https://www.npmjs.com/package/chrome-extension-async

**Comment by bigandy** [comment]
@KeithHenry Thanks!
