### ISSUE TITLE
Namespace chrome.sockets.* is missing from typescript file

### ISSUE THREAD

**Issue by aeons** [KeithHenry/chromeExtensionAsync#16]
If the typescript definitions are generated somehow, it should probably be regenerated.

**Comment by KeithHenry** [comment]
@aeons They aren't, as the supported list is hand coded the definitions are too. I haven't found a reliable way to auto-detect which Chrome API calls can be promisified with the pattern, so the supported selection is kind of a whitelist of ones that work.

`chrome.sockets.*` needs adding to the TS definitions.

**Comment by UrielCh** [comment]
chrome.debugger.* is also missing.

**Comment by UrielCh** [comment]
thx.
