### ISSUE TITLE
Uncaught ReferenceError: secondsToTimeout is not defined

### ISSUE THREAD

**Issue by toancong** [KeithHenry/chromeExtensionAsync#21]
Please take a look at this error. Thanks.
Uncaught ReferenceError: secondsToTimeout is not defined
https://github.com/KeithHenry/chromeExtensionAsync/blob/master/execute-async-function.js#L133

**Comment by KeithHenry** [comment]
Fixed in 3.4.1, now on https://www.npmjs.com/package/chrome-extension-async
