### ISSUE TITLE
try-catch in event listeners

### ISSUE THREAD

**Issue by avalanche1** [KeithHenry/chromeExtensionAsync#22]
Is try-catch error handling described [here](https://github.com/KeithHenry/chromeExtensionAsync#examples) supposed to work when I await for an async function inside of an event listener callback? 
`content-script.js`
```typescript
chrome.runtime.onMessage.addListener(async (message, sender, sendResponse) => {
 const message1: SendInputMessage = {
    type: EXTENSION_COMMANDS.AC.SEND_INPUT,
    // tabId: get_active_tab_id(EXTENSION_COMMANDS.AC.SEND_INPUT),
    method: "Input.insertText",
    params: {
      text: 'BGAvalue',
    },
  };
  try {
    await chrome.runtime.sendMessage(message1);
  } catch (error) {
    console.error(error);
  }

  return true;
});
```
`background.js`
```typescript
chrome.runtime.onMessage.addListener(async (message: SendInputMessage, sender) => {
  if (message.type !== EXTENSION_COMMANDS.AC.SEND_INPUT) return undefined;
  try {
    const activeTabId = (sender.tab as Tab).id;

    // Check if debugger is not yet attached to the tab.
    const allTabs = await chrome.debugger.getTargets(
      () => {}
    )
    const debuggerIsNotYetAttachedToTab = allTabs.some(
      (target) => target.tabId === activeTabId
    );

    // Attach debugger to the tab.
    const targetTab = {tabId: activeTabId};
    if (debuggerIsNotYetAttachedToTab) {
      const devtoolsProtocolVersion = "1.3";
      await chrome.debugger.attach(targetTab, devtoolsProtocolVersion);
    }

    chrome.debugger.sendCommand(targetTab, message.method, message.params);
  } catch (error) {
    console.error(error);
  }

  return true;
});
```

And I always get this in both files' consoles when exchanging messages:
![image](https://user-images.githubusercontent.com/10534563/67660746-8daba300-f970-11e9-83c3-86f021e4cbf1.png)

**Comment by KeithHenry** [comment]
Mostly yes, though your last `sendCommand` won't because it doesn't have an `await`.

I'm a little confused though - in your `catch` block you're writing the error to the console, which is what you see when you get the error. Is that not expected?

**Comment by avalanche1** [comment]
It's just for demonstration purposes. Although, yep, a bit confusing. 
But as you can see - the console says `Uncaught` - whereas if `console.error` was hit - it wouldn't say that.

**Comment by KeithHenry** [comment]
@avalanche1 Yes, the missing `await` before the last `sendCommand` means that any errors in that error are _not_ caught - `try-catch` _only_ works on promises that you `await`, otherwise you have to use the `.catch` syntax.
