### ISSUE TITLE
other browser compatability

### ISSUE THREAD

**Issue by masihfathi** [KeithHenry/chromeExtensionAsync#6]
hi, dose this wrapper work for other browsers? and how is it possible to work with single code for all browsers? i know firefox compatible with chrome namespace but how it is possible to do with single code for all browsers and rescue from callback hell?

**Comment by KeithHenry** [comment]
I think Firefox's implementation of Chrome's API already adds async support, but if not it could be adapted easily enough. It's using ES2017 features, but I'm fairly sure FX supports them all, so you could try it and see (both bugs and PRs welcome)
