### ISSUE TITLE
Transpile chromeExtensionAsync to ES5 to support minification on other projects

### ISSUE THREAD

**Issue by sag1v** [KeithHenry/chromeExtensionAsync#8]
It would be great if `chromeExtensionAsync` will transpile to ES5 so it can be minified as a part of a build process inside other projects.  

My specific use case was that i wanted to use it as part of a `react`  project (while using [create-react-app](https://github.com/facebook/create-react-app)) and when i tried to build i got the error:  

> Failed to minify the code from this file:
./node_modules/chrome-extension-async/chrome-extension-async.js:13

In this case, [line13  ](https://github.com/KeithHenry/chromeExtensionAsync/blob/8952e249e790a4034caaf82eea653873abf5e417/chrome-extension-async.js#L13) is using the [ES2015 rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters).

You can read about the motivation behind this behavior [here ](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify).
I'm sure there are other scenarios other than mine.

My suggestion is to create a build process for `chromeExtensionAsync`.
We can use [npm scripts](https://docs.npmjs.com/misc/scripts) for the build script, and [babel](https://babeljs.io/) for the compilation.  

babel has a great [preset](https://babeljs.io/docs/en/babel-preset-env/) to cover most if not all of the latest features of ES and transpile them to ES5.

**Comment by KeithHenry** [comment]
Resolved by #9, release in v3.3.0
